create table public.fsk_cert (
  id integer generated by default as identity not null,
  cert_file_name text not null,
  cat_id integer not null default 1,
  cert_name text not null,
  cert_description text null,
  cert_feature_image text null,
  cert_instructor text null,
  created_at timestamp with time zone null,
  updated_at timestamp with time zone null,
  weight integer not null default 0,
  cert_slug text null,
  constraint fsk_cert_pkey primary key (id),
  constraint FK_fsk_cert_fsk_cert_cat foreign KEY (cat_id) references fsk_cert_cat (id) on update CASCADE on delete CASCADE,
  constraint fsk_cert_cat_id_check check ((cat_id > 0)),
  constraint fsk_cert_id_check check ((id > 0))
) TABLESPACE pg_default;