create table public.fsk_cert_tag_type (
  id integer generated by default as identity not null,
  name text not null,
  description text not null,
  created_at timestamp with time zone null,
  updated_at timestamp with time zone null,
  count integer null,
  constraint fsk_cert_tag_type_pkey primary key (id),
  constraint fsk_cert_tag_type_id_check check ((id > 0))
) TABLESPACE pg_default;