create table public.fsk_cert_cat (
  id integer generated by default as identity not null,
  cat_name character varying(191) not null,
  cat_description text not null,
  cat_icon_name text not null,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  constraint fsk_cert_cat_pkey primary key (id),
  constraint fsk_cert_cat_id_check1 check ((id > 0))
) TABLESPACE pg_default;