create table public.fsk_prj_tech_type (
  id integer generated by default as identity not null,
  name character varying(191) not null,
  description text null,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  constraint fsk_prj_tech_type_pkey primary key (id),
  constraint fsk_prj_tech_type_id_check check ((id > 0))
) TABLESPACE pg_default;