[build]
  command = "npm run build"
  publish = "build"
  edge_functions = "edge-functions"

[[edge_functions]]
  path = "/edge-api/index/email"
  function = "email"

[[edge_functions]]
  path = "/edge-api/cert/get/tags"
  function = "gettags"

[[edge_functions]]
  path = "/edge-api/test"
  function = "test"

[[redirects]]
  from = "/pt/gmt"
  to = "https://www.googletagmanager.com/gtag/js"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/pt/hcaptcha"
  to = "https://js.hcaptcha.com/1/api.js"
  status = 200
  force = true
  headers = {X-From = "Netlify"}