[build]
  command = "npm run build"
  publish = "build"
  edge_functions = "edge-functions"

[[edge_functions]]
  path = "/edge-api/index/email"
  function = "email"

[[edge_functions]]
  path = "/edge-api/cert/get/tags"
  function = "gettags"

[[edge_functions]]
  path = "/edge-api/test"
  function = "test"
