create table public.fsk_github_contributions (
  id bigint generated by default as identity not null,
  html text null,
  updated_at timestamp with time zone not null default now(),
  constraint fsk_github_contributions_pkey primary key (id)
) TABLESPACE pg_default;